import { createContext, useState, useEffect } from "react";
import { fetchAmounts } from '../services/api.js'

export const CurrencyContext = createContext()

export const CurrencyProvider = ({ children }) => {
  const [currencyRates, setCurrencyRates] = useState({})
  const countries = {
    "USD": "US",
    "AED": "AE",
    "AFN": "AF",
    "ALL": "AL",
    "AMD": "AM",
    "ANG": "CW",
    "AOA": "AO",
    "ARS": "AR",
    "AUD": "AU",
    "AWG": "AW",
    "AZN": "AZ",
    "BAM": "BA",
    "BBD": "BB",
    "BDT": "BD",
    "BGN": "BG",
    "BHD": "BH",
    "BIF": "BI",
    "BMD": "BM",
    "BND": "BN",
    "BOB": "BO",
    "BRL": "BR",
    "BSD": "BS",
    "BTN": "BT",
    "BWP": "BW",
    "BYN": "BY",
    "BZD": "BZ",
    "CAD": "CA",
    "CDF": "CD",
    "CHF": "CH",
    "CLP": "CL",
    "CNY": "CN",
    "COP": "CO",
    "CRC": "CR",
    "CUP": "CU",
    "CVE": "CV",
    "CZK": "CZ",
    "DJF": "DJ",
    "DKK": "DK",
    "DOP": "DO",
    "DZD": "DZ",
    "EGP": "EG",
    "ERN": "ER",
    "ETB": "ET",
    "EUR": "EU",
    "FJD": "FJ",
    "FKP": "FK",
    "FOK": "FO",
    "FI": "FI",
    "FR": "FR",
    "GA": "GA",
    "GM": "GM",
    "GE": "GE",
    "GH": "GH",
    "GIP": "GI",
    "GL": "GL",
    "GN": "GN",
    "GQ": "GQ",
    "GR": "GR",
    "GTQ": "GT",
    "GYD": "GY",
    "HKD": "HK",
    "HNL": "HN",
    "HRK": "HR",
    "HTG": "HT",
    "HUF": "HU",
    "IDR": "ID",
    "IE": "IE",
    "ILS": "IL",
    "IMP": "IM",
    "INR": "IN",
    "IQD": "IQ",
    "IRR": "IR",
    "ISK": "IS",
    "JEP": "JE",
    "JMD": "JM",
    "JOD": "JO",
    "JPY": "JP",
    "KES": "KE",
    "KGS": "KG",
    "KHR": "KH",
    "KID": "KI",
    "KMF": "KM",
    "KRW": "KR",
    "KWD": "KW",
    "KYD": "KY",
    "KZT": "KZ",
    "LAK": "LA",
    "LBP": "LB",
    "LKR": "LK",
    "LRD": "LR",
    "LSL": "LS",
    "LYD": "LY",
    "MAD": "MA",
    "MDL": "MD",
    "MGA": "MG",
    "MKD": "MK",
    "MMK": "MM",
    "MNT": "MN",
    "MOP": "MO",
    "MRU": "MR",
    "MUR": "MU",
    "MVR": "MV",
    "MWK": "MW",
    "MXN": "MX",
    "MYR": "MY",
    "MZN": "MZ",
    "NAD": "NA",
    "NGN": "NG",
    "NIO": "NI",
    "NL": "NL",
    "NO": "NO",
    "NP": "NP",
    "NZD": "NZ",
    "OMR": "OM",
    "PAB": "PA",
    "PEN": "PE",
    "PGK": "PG",
    "PHP": "PH",
    "PKR": "PK",
    "PLN": "PL",
    "PYG": "PY",
    "QAR": "QA",
    "RON": "RO",
    "RSD": "RS",
    "RUB": "RU",
    "RWF": "RW",
    "SAR": "SA",
    "SBD": "SB",
    "SCR": "SC",
    "SDG": "SD",
    "SEK": "SE",
    "SGD": "SG",
    "SHP": "SH",
    "SL": "SL",
    "SLL": "SLL",
    "SOS": "SO",
    "SRD": "SR",
    "SSP": "SS",
    "STN": "ST",
    "SYP": "SY",
    "SZL": "SZ",
    "THB": "TH",
    "TJS": "TJ",
    "TMT": "TM",
    "TND": "TN",
    "TOP": "TO",
    "TRY": "TR",
    "TTD": "TT",
    "TVD": "TV",
    "TWD": "TW",
    "TZS": "TZ",
    "UAH": "UA",
    "UGX": "UG",
    "UYU": "UY",
    "UZS": "UZ",
    "VES": "VE",
    "VND": "VN",
    "VUV": "VU",
    "WST": "WS",
    "XAF": "XAF",
    "XCD": "XCD",
    "XDR": "XDR",
    "XOF": "XOF",
    "XPF": "XPF",
    "YER": "YE",
    "ZAR": "ZA",
    "ZMW": "ZM",
    "ZWL": "ZW"
  }
  
  useEffect(() => {
    fetchAmounts('USD').then((data) => {
      setCurrencyRates(data)
    })
  }, [])

  return (
    <CurrencyContext.Provider value={{ currencyRates, countries }}>
      { children }
    </CurrencyContext.Provider>
  )
}
